
channels:
  - conda-forge
  - serge-sans-paille

dependencies:
  - python=3.6
  - numpy
  - cython
  - mpi4py
  - h5py
  - sphinx
  - numpydoc
  - jupyter
  - matplotlib
  - fftw
  - pyfftw
  - pythran
